NEGRO = (0, 0, 0)
BLANCO = (255, 255, 255)

BALDOSA_TAMANIO = 30
BALDOSA_NUMERO = 25
MARCADOR_ALTURA = 32

ANCHURA = BALDOSA_TAMANIO * BALDOSA_NUMERO
ALTURA = BALDOSA_TAMANIO * BALDOSA_NUMERO + MARCADOR_ALTURA

PUNTO_UNIDAD = 1